/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ratusapparatus_passssh_PassSSH */

#ifndef _Included_com_ratusapparatus_passssh_PassSSH
#define _Included_com_ratusapparatus_passssh_PassSSH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ratusapparatus_passssh_PassSSH
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lcom/ratusapparatus/passssh/PassSSH/AuthType;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ratusapparatus_passssh_PassSSH_Init
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     com_ratusapparatus_passssh_PassSSH
 * Method:    GetPassIDs
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_ratusapparatus_passssh_PassSSH_GetPassIDs
  (JNIEnv *, jobject);

/*
 * Class:     com_ratusapparatus_passssh_PassSSH
 * Method:    GetPass
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ratusapparatus_passssh_PassSSH_GetPass
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ratusapparatus_passssh_PassSSH
 * Method:    InsertPass
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ratusapparatus_passssh_PassSSH_InsertPass
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ratusapparatus_passssh_PassSSH
 * Method:    GeneratePass
 * Signature: (Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_com_ratusapparatus_passssh_PassSSH_GeneratePass
  (JNIEnv *, jobject, jstring, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ratusapparatus_passssh_PassSSH_AuthType */

#ifndef _Included_com_ratusapparatus_passssh_PassSSH_AuthType
#define _Included_com_ratusapparatus_passssh_PassSSH_AuthType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
